import { IDefinition, IScriptsOutput } from "../../types";
import { AUTOGENERATED_ALERT } from "../constructions/terminals";
import { composeDomainHelper } from "./domain_helper.compose";
import { composeIndex } from "./index.compose";
import { composeTests } from "./tests.compose";
import { composeTypes } from "./types.compose";
import { composeUtils } from "./utils.compose";

export function build(def: IDefinition): IScriptsOutput {
  return {
    tests: AUTOGENERATED_ALERT + composeTests(def),
    types: AUTOGENERATED_ALERT + composeTypes(def),
    utils: AUTOGENERATED_ALERT + composeUtils(def),
    index: AUTOGENERATED_ALERT + composeIndex(def),
    domain: AUTOGENERATED_ALERT + composeDomainHelper(def),
  };
}
