import { IDefinition } from "../../types";
import {
    buildTestSuite,
} from "../constructions/nonterminals";

export const composeTests = (def: IDefinition) => {

    return `

    /*
    *   Autogenerated code
    *   Source: https://gitlab.com/guardian-network/polemos-contracts/eip712-signature-infrastructure-generator
    *   DO NOT MODIFY
    */

    ${buildTestSuite(def)}
    `;
}