import { IDefinition } from "../../types";
import {
    buildMessageType,
    buildEIP712MessageTypes
} from "../constructions/nonterminals";
import { EIP712DomainType, ParamType } from "../constructions/terminals";

export const composeTypes = (def: IDefinition) => {

    return `

    /*
    *   Autogenerated code
    *   Source: https://gitlab.com/guardian-network/polemos-contracts/eip712-signature-infrastructure-generator
    *   DO NOT MODIFY
    */
   
    import { BytesLike, BigNumberish } from 'ethers';

    ${buildMessageType(def)}

    ${buildEIP712MessageTypes(def)}

    ${ParamType}

    ${EIP712DomainType}
    `;
}