import { IDefinition } from "../../types";
import {
    buildMessage,
    buildSignedMessage,
} from "../constructions/nonterminals";

export const composeUtils = (def: IDefinition) => {
    return `

    /*
    *   Autogenerated code
    *   Source: https://gitlab.com/guardian-network/polemos-contracts/eip712-signature-infrastructure-generator
    *   DO NOT MODIFY
    */
   
    import {SignerWithAddress} from "@nomiclabs/hardhat-ethers/signers";
    import { BigNumberish } from "ethers";
    import { ${def.struct.map(el => `${el.name}Message, ${el.name}Type`).join(', ')}, EIP712DomainType, ${def.related.map(el => `${el.name}Type`).join(', ')} } from "./message.types";

    ${buildMessage(def)}

    ${buildSignedMessage(def)}
    `;
}