/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ERC1271Contract,
  ERC1271ContractInterface,
} from "../../Utils.sol/ERC1271Contract";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_hash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_signature",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bytes4",
        name: "magicValue",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ERC1271Contract__factory {
  static readonly abi = _abi;
  static createInterface(): ERC1271ContractInterface {
    return new utils.Interface(_abi) as ERC1271ContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1271Contract {
    return new Contract(address, _abi, signerOrProvider) as ERC1271Contract;
  }
}
