export const OUTPUT_CONTRACTS_PATH = "OUTPUT_CONTRACTS_PATH";
export const OUTPUT_TESTS_PATH = "OUTPUT_TESTS_PATH";
export const OUTPUT_CACHE_PATH = "OUTPUT_CACHE_PATH";
export const OUTPUT_ARTIFACTS_PATH = "OUTPUT_ARTIFACTS_PATH";