import { IContractsOutput, IDefinition } from "../../types";
import { AUTOGENERATED_ALERT } from "../constructions/terminals";
import { composeLib } from "./lib.compose";
import { composeParams } from "./params.compose";
import { composeTypehash } from "./typehash.compose";
import { composeUtilLib } from "./utilLib.compose";
import { composeUtils } from "./utils.compose";

export function build(def: IDefinition, name: string): IContractsOutput {
  return {
    recoveryLib: AUTOGENERATED_ALERT + composeLib(def, name),
    typeHashDefinitions: AUTOGENERATED_ALERT + composeTypehash(def),
    params: AUTOGENERATED_ALERT + composeParams(def),
    mayNeed: AUTOGENERATED_ALERT + composeUtils(def),
    utilLib: AUTOGENERATED_ALERT + composeUtilLib(),
  };
}
