import { IDefinition } from "../../types";
import { buildStubTypeHash, buildTypeHash } from "../constructions/nonterminals";
import { UNLICENSED_LICENSE, SOLIDITY_19, DOMAIN_TYPEHASH_WITH_SALT, DOMAIN_TYPEHASH } from "../constructions/terminals";

export const composeTypehash = (def: IDefinition) => {

    return `

    /*
    *   Autogenerated code
    *   Source: https://gitlab.com/guardian-network/polemos-contracts/eip712-signature-infrastructure-generator
    *   DO NOT MODIFY
    */
    
    ${UNLICENSED_LICENSE}
    ${SOLIDITY_19}

    ${def.domain.salt ? DOMAIN_TYPEHASH_WITH_SALT : DOMAIN_TYPEHASH}

    ${buildTypeHash(def)}

    ${buildStubTypeHash(def)}
    `;
}