import { IDefinition } from "../../types";
import { ERC1271, SOLIDITY_19, UNLICENSED_LICENSE } from "../constructions/terminals";

export const composeUtils = (def: IDefinition) => {
    
    return `

    /*
    *   Autogenerated code
    *   Source: https://gitlab.com/guardian-network/polemos-contracts/eip712-signature-infrastructure-generator
    *   DO NOT MODIFY
    */

    ${UNLICENSED_LICENSE}
    ${SOLIDITY_19}
    
    ${ERC1271}

    `;
}